import type { CategorySlug } from "./types";

export const CATEGORY_KEYWORDS: Record<CategorySlug, string[]> = {
  food: [
    "WARUNG",
    "RESTO",
    "RESTORAN",
    "CAFE",
    "KAFE",
    "KOPI",
    "KOPI NAKO",
    "KOPI KENANGAN",
    "TOMORO",
    "FORE",
    "FORE COFFEE",
    "POINT COFFEE",
    "JANJI JIWA",
    "COFFEE",
    "BAKSO",
    "AYAM",
    "NASI",
    "MIE",
    "MIE GACOAN",
    "GACOAN",
    "SATE",
    "SOTO",
    "RAWON",
    "PECEL",
    "PENYET",
    "GEPREK",
    "BEBEK",
    "SEAFOOD",
    "IKAN",
    "STEAK",
    "SUSHI",
    "RAMEN",
    "DIMSUM",
    "GORENGAN",
    "MARTABAK",
    "ROTI BAKAR",
    "BAKERY",
    "ROTI",
    "ROTI O",
    "ROTI'O",
    "BREADTALK",
    "MAKO",
    "HOLLAND BAKERY",
    "TOUS LES JOURS",
    "KFC",
    "SOLARIA",
    "MCD",
    "MCDONALDS",
    "STARBUCKS",
    "CHATIME",
    "HAUS",
    "MIXUE",
    "JCO",
    "HOKBEN",
    "HOKA HOKA BENTO",
    "A&W",
    "RICHEESE",
    "RICHEESE FACTORY",
    "BURGER KING",
    "PIZZA",
    "PIZZA HUT",
    "DOMINOS",
    "SUBWAY",
    "MARUGAME",
    "MARUGAME UDON",
    "YOSHINOYA",
    "PEPPER LUNCH",
    "KINTAN",
    "SHABURI",
    "D'COST",
    "TA WAN",
    "WARKOP",
    "WARTEG",
    "SEDERHANA",
    "PADANG",
    "RUMAH MAKAN",
    "DAPUR",
    "KULINER",
    "BISTRO",
    "EATERY",
    "KANTIN",
    "ES TEH",
    "ESTEH",
    "TEGUK",
    "MENANTEA",
    "KOI THE",
    "BOBA",
    "JUS",
    "ICE CREAM",
    "GELATO",
    "GOFOOD",
    "GO-FOOD",
    "GRABFOOD",
    "GRAB-FOOD",
    "SHOPEEFOOD",
    "SHOPEE-FOOD",
    "MAKAN",
    "MINUM",
    "BEVERAGE",
    "FOOD",
    "DINE-IN",
    "TAKE AWAY",
    "TAKEAWAY",
  ],
  transport: [
    "GRAB",
    "GOJEK",
    "GO-JEK",
    "GORIDE",
    "GO-RIDE",
    "GOCAR",
    "GO-CAR",
    "GRABRIDE",
    "GRABCAR",
    "MAXIM",
    "INDRIVER",
    "BLUEBIRD",
    "MYBLUEBIRD",
    "TAKSI",
    "PARKIR",
    "PARKING",
    "SECURE PARKING",
    "SKY PARKING",
    "VALET",
    "TOL",
    "TARIF TOL",
    "GERBANG TOL",
    "JASA MARGA",
    "E-TOLL",
    "ETOLL",
    "PERTAMINA",
    "SHELL",
    "BP-AKR",
    "BP AKR",
    "VIVO",
    "REVVO",
    "BENSIN",
    "PERTALITE",
    "PERTAMAX",
    "SOLAR",
    "DEXLITE",
    "BBM",
    "SPBU",
    "TRANSJAKARTA",
    "BUSWAY",
    "KAI",
    "KERETA API",
    "KAI ACCESS",
    "ACCESS BY KAI",
    "COMMUTER LINE",
    "KAI COMMUTER",
    "MRT",
    "LRT",
    "DAMRI",
    "ANGKOT",
    "TIKET KERETA",
    "TIKET PESAWAT",
    "GARUDA",
    "LION AIR",
    "CITILINK",
    "BATIK AIR",
    "AIRASIA",
    "ASDP",
    "PENYEBERANGAN",
    "BENGKEL",
    "TAMBAL BAN",
    "CUCI MOTOR",
    "CUCI MOBIL",
    "CUCI STEAM",
    "TRANSPORTASI",
  ],
  shopping: [
    "INDOMARET",
    "ALFAMART",
    "ALFAMIDI",
    "SUPERINDO",
    "HYPERMART",
    "TRANSMART",
    "LOTTE MART",
    "LOTTEMART",
    "HERO",
    "RANCH MARKET",
    "FARMERS MARKET",
    "GRAND LUCKY",
    "GS THE FRESH",
    "CIRCLE K",
    "FAMILYMART",
    "LAWSON",
    "TOKOPEDIA",
    "SHOPEE",
    "LAZADA",
    "BLIBLI",
    "TIKTOK SHOP",
    "MINISO",
    "UNIQLO",
    "H&M",
    "ZARA",
    "PULL&BEAR",
    "BERSHKA",
    "STRADIVARIUS",
    "COTTON ON",
    "MATAHARI",
    "RAMAYANA",
    "SOGO",
    "SEIBU",
    "METRO",
    "WATSONS",
    "ACE HARDWARE",
    "INFORMA",
    "IKEA",
    "MR DIY",
    "MR. DIY",
    "KKV",
    "OH SOME",
    "ERIGO",
    "3SECOND",
    "SPORTS STATION",
    "FOOT LOCKER",
    "DECATHLON",
    "BELANJA",
    "SWALAYAN",
    "MINIMARKET",
    "SUPERMARKET",
    "TOKO",
    "TOSERBA",
    "GROSIR",
    "DISTRO",
    "BUTIK",
    "MALL",
    "PLAZA",
    "PASAR",
  ],
  bills: [
    "PLN",
    "TOKEN LISTRIK",
    "TOKEN PLN",
    "LISTRIK PINTAR",
    "PDAM",
    "PAM JAYA",
    "PERUMDA AIR",
    "TAGIHAN AIR",
    "INDIHOME",
    "TELKOM",
    "MYREPUBLIC",
    "BIZNET",
    "FIRST MEDIA",
    "OXYGEN.ID",
    "CBN",
    "INTERNET",
    "WIFI",
    "BPJS",
    "BPJS KESEHATAN",
    "BPJS KETENAGAKERJAAN",
    "PULSA",
    "PAKET DATA",
    "TAGIHAN",
    "LISTRIK",
    "PASCABAYAR",
    "PRABAYAR",
    "TELKOMSEL",
    "BY.U",
    "BYU",
    "INDOSAT",
    "IM3",
    "XL",
    "AXIS",
    "SMARTFREN",
    "TRI",
    "KARTU HALO",
    "PGN",
    "GAS NEGARA",
    "PBB",
    "PAJAK",
    "SAMSAT",
    "IURAN",
    "IPL",
    "CICILAN",
    "ANGSURAN",
    "MULTIFINANCE",
    "KREDIT",
    "HOME CREDIT",
    "FIF",
    "ADIRA",
    "BFI",
    "KREDIVO",
    "SPAYLATER",
    "GOPAYLATER",
    "AKULAKU",
  ],
  transfer: [
    "TRANSFER",
    "DITRANSFER",
    "M-TRANSFER",
    "M TRANSFER",
    "MYBCA",
    "TRANSFER BERHASIL",
    "TRANSFER SUCCESSFUL",
    "BUKTI TRANSFER",
    "SENT TO BANK",
    "TRANSFER DETAILS",
    "DITRANSFER KE",
    "TRANSFER KE",
    "TRANSFER RUPIAH",
    "TRANSFER DANA",
    "TRANSFER SALDO",
    "KIRIM UANG",
    "KIRIM DANA",
    "KIRIM SALDO",
    "KIRIM KE BANK",
    "BI-FAST",
    "BI FAST",
    "REALTIME ONLINE",
    "REAL TIME ONLINE",
    "SKN",
    "KLIRING",
    "REK PEMINDAHAN",
    "REKENING TUJUAN",
    "NOMOR REKENING",
    "NO REK",
    "BENEFICIARY NAME",
    "BENEFICIARY ACCOUNT",
    "PENERIMA TRANSFER",
    "SEABANK",
    "BANK JAGO",
    "JAGO",
    "BLU BY BCA",
    "ALOBANK",
    "NEOBANK",
    "BANK NEO",
    "FLIP",
  ],
  entertainment: [
    "CGV",
    "XXI",
    "CINEMA XXI",
    "CINEMA 21",
    "CINEPOLIS",
    "PREMIERE",
    "IMAX",
    "BIOSKOP",
    "CINEMA",
    "TIKET BIOSKOP",
    "TIKET KONSER",
    "NETFLIX",
    "SPOTIFY",
    "APPLE MUSIC",
    "APPLE TV",
    "YOUTUBE PREMIUM",
    "DISNEY",
    "DISNEY+",
    "HOTSTAR",
    "VIDIO",
    "HBO GO",
    "PRIME VIDEO",
    "WE TV",
    "WETV",
    "IQIYI",
    "STEAM",
    "PLAYSTATION",
    "PS STORE",
    "NINTENDO",
    "XBOX",
    "EPIC GAMES",
    "ROBLOX",
    "VALORANT",
    "MOBILE LEGENDS",
    "TOPUP GAME",
    "TOP UP GAME",
    "UNIPIN",
    "CODASHOP",
    "TIMEZONE",
    "AMAZONE",
    "DUFAN",
    "ANCOL",
    "TRANS STUDIO",
    "WATERPARK",
    "TAMAN SAFARI",
    "KARAOKE",
    "BILLIARD",
    "BOWLING",
    "GAME",
    "KONSER",
    "FESTIVAL",
  ],
  health: [
    "APOTEK",
    "APOTIK",
    "K24",
    "K-24",
    "APOTEK K-24",
    "KIMIA FARMA",
    "CENTURY",
    "GUARDIAN",
    "WATSONS HEALTH",
    "KLINIK",
    "KLINIK GIGI",
    "RUMAH SAKIT",
    "RSUD",
    "RSIA",
    "RSU",
    "DOKTER",
    "DOKTER GIGI",
    "RESEP DOKTER",
    "PUSKESMAS",
    "HALODOC",
    "ALODOKTER",
    "OBAT",
    "VITAMIN",
    "LAB",
    "LABORATORIUM",
    "PRODIA",
    "PRAMITA",
    "SILOAM",
    "HERMINA",
    "MITRA KELUARGA",
    "MAYAPADA",
    "CIPUTRA HOSPITAL",
    "BIDAN",
    "DENTAL",
    "OPTIK",
    "OPTIK MELAWAI",
    "OPTIK SEIS",
    "OPTIK TUNGGAL",
    "KACAMATA",
    "SOFTLENS",
    "FARMASI",
    "MEDIS",
    "FISIOTERAPI",
  ],
  education: [
    "BUKU",
    "TOKO BUKU",
    "GRAMEDIA",
    "PERIPLUS",
    "TOGAMAS",
    "STATIONERY",
    "ATK",
    "FOTOKOPI",
    "FOTO KOPI",
    "KURSUS",
    "BIMBEL",
    "KUMON",
    "GANESHA OPERATION",
    "INTEN",
    "NURUL FIKRI",
    "ZENIUS",
    "RUANGGURU",
    "PAHAMIFY",
    "UDEMY",
    "COURSERA",
    "SKILL ACADEMY",
    "UKT",
    "SPP",
    "BIAYA KULIAH",
    "BIAYA SEKOLAH",
    "SEKOLAH",
    "KAMPUS",
    "KULIAH",
    "SEMINAR",
    "WORKSHOP",
    "WISUDA",
    "SKRIPSI",
    "SERTIFIKASI",
    "TOEFL",
    "IELTS",
    "PERPUSTAKAAN",
  ],
  other: [],
};
